name: dw_application
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  nfc_manager: ^3.0.0 
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  searchable_listview: ^2.15.2
  dio: ^5.4.3+1
  shared_preferences: ^2.3.3
  settings_ui: 
    git:
      url: https://github.com/yako-dev/flutter-settings-ui
      ref: 56f4f1b812b76d95ac86377504bc6bb144718497

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  intl_translation: ^0.20.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/example.json
    - assets/images/
